[package]
name = "markora"
version = "0.1.0"
description = "Markora local-first Markdown editor"
authors = ["Sanskar <sanskarin@outlook.in>"]
edition = "2024"
license = "MIT"
rust-version = "1.85"

[lib]
name = "markora_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = "2.6.3"

[dependencies]
serde = { version = "1", features = ["derive"] }
tauri = { version = "2.11.5" }
tauri-plugin-dialog = "2.7.2"
tauri-plugin-fs = "2.4.4"
tauri-plugin-opener = "2.5.0"
tauri-plugin-persisted-scope = "2.3.3"
tempfile = "3.27"
url = "2"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
open = "5"
rfd = "0.15"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
