[package]
name = "tauri-plugin-markora-document-io"
version = "0.1.0"
edition = "2021"
links = "markora-document-io"
license = "MIT"
publish = false

[dependencies]
serde = { version = "1", features = ["derive"] }
tauri = "2.11.5"
thiserror = "2"

[target.'cfg(target_os = "android")'.dependencies]
tauri = { version = "2.11.5", features = ["wry"] }

[build-dependencies]
tauri-plugin = { version = "2", features = ["build"] }
